name: Go
on: [push, pull_request]
jobs:
  tests:
     name: Test on go ${{ matrix.go_version }}
     runs-on: [ubuntu-latest]
     strategy:
       matrix:
         go_version: [1.13, '']
     steps:
       - uses: actions/checkout@v1
       - name: Use golang ${{ matrix.go_version }}
         uses: actions/setup-go@v1
         with:
           go-version: ${{ matrix.go_version }} 
           
       - name: Go version
         run: |
           go version
           
       - name: Go get dependencies
         run: |
           go get -v -t -d ./...

       - name: Run tests
         run: |
          go test ./... -count=1 -race -cover
         if: matrix.go_version != 1.13
         continue-on-error: true
          
       - name: Build
         if: matrix.go_version == 1.13
         run: |
           go build -v .
          
